[package]
name = "app_ergo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ergo-lib = "0.28.0"
hex = {workspace = true}
thiserror = { workspace = true }

[dev-dependencies]
keystore = { workspace = true }
